# Apple Graphite System Dark

background = #1E1E1E
foreground = #DEDEDE

cursor-color = #3C82F7
cursor-text = #1E1E1E

selection-background = #4E6B92
selection-foreground = #FFFFFF

split-divider-color = #444444
minimum-contrast = 1.1

palette = 0=#1B1B1B
palette = 1=#F06461
palette = 2=#7FC05B
palette = 3=#F8CE4D
palette = 4=#3C82F7
palette = 5=#A05AB0
palette = 6=#56C0D8
palette = 7=#E9E9E9

palette = 8=#606060
palette = 9=#F06461
palette = 10=#7FC05B
palette = 11=#F8CE4D
palette = 12=#6A76F0
palette = 13=#EA63A4
palette = 14=#4FAE9B
palette = 15=#FFFFFF

palette-generate = true
palette-harmonious = false

bold-color = #FFFFFF
