# Apple Graphite Expanded Light

background = #FFFFFF
foreground = #272727

cursor-color = #3477F7
cursor-text = #FFFFFF

selection-background = #BAD6FB
selection-foreground = #000000

split-divider-color = #EBEBEB
minimum-contrast = 1.1

palette = 0=#272727
palette = 1=#CE4745
palette = 2=#78B856
palette = 3=#F6C94E
palette = 4=#3477F7
palette = 5=#8B4292
palette = 6=#4DAFC3
palette = 7=#F7F7F7

palette = 8=#7F7F7F
palette = 9=#CE4745
palette = 10=#78B856
palette = 11=#F6C94E
palette = 12=#6559CC
palette = 13=#E45C9D
palette = 14=#5A9B90
palette = 15=#FFFFFF

palette-generate = true
palette-harmonious = true

bold-color = #000000
