# Apple Graphite System Light

background = #FFFFFF
foreground = #272727

cursor-color = #3B81F8
cursor-text = #FFFFFF

selection-background = #C1DBFD
selection-foreground = #000000

split-divider-color = #EBEBEB
minimum-contrast = 1.1

palette = 0=#272727
palette = 1=#D6514E
palette = 2=#7FBE5C
palette = 3=#F8CC56
palette = 4=#3B81F8
palette = 5=#93499B
palette = 6=#45B8D4
palette = 7=#F7F7F7

palette = 8=#7F7F7F
palette = 9=#D6514E
palette = 10=#7FBE5C
palette = 11=#F8CC56
palette = 12=#5E69DD
palette = 13=#EA63A4
palette = 14=#479C8E
palette = 15=#FFFFFF

palette-generate = true
palette-harmonious = true

bold-color = #000000
