# Apple Graphite Expanded Dark

background = #1E1E1E
foreground = #DEDEDE

cursor-color = #3478F6
cursor-text = #1E1E1E

selection-background = #476288
selection-foreground = #FFFFFF

split-divider-color = #444444
minimum-contrast = 1.1

palette = 0=#1B1B1B
palette = 1=#EC5F5D
palette = 2=#78B855
palette = 3=#F6C944
palette = 4=#3478F6
palette = 5=#9955A3
palette = 6=#59B7C9
palette = 7=#E9E9E9

palette = 8=#606060
palette = 9=#EC5F5D
palette = 10=#78B855
palette = 11=#F6C944
palette = 12=#6F63D9
palette = 13=#E45C9D
palette = 14=#5FA79B
palette = 15=#FFFFFF

palette-generate = true
palette-harmonious = false

bold-color = #FFFFFF
