# Islands Dark
background = #191A1C
foreground = #BCBEC4
cursor-color = #CED0D6
cursor-text = #191A1C
selection-background = #373B39
selection-foreground = #DFE1E5
palette = 0=#191A1C
palette = 1=#F75464
palette = 2=#6AAB73
palette = 3=#E0BB65
palette = 4=#56A8F5
palette = 5=#C77DBB
palette = 6=#2AACB8
palette = 7=#BCBEC4
palette = 8=#6F737A
palette = 9=#FA6675
palette = 10=#73BD79
palette = 11=#F2C55C
palette = 12=#70AEFF
palette = 13=#CF84CF
palette = 14=#42C3D4
palette = 15=#CED0D6
