# shellcheck shell=bash
# shellcheck disable=SC2034,SC2154
# zsh-syntax-highlighting styles (mac-dev-setup)

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=160'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=33,bold'
ZSH_HIGHLIGHT_STYLES[alias]='fg=75'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=75'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=39'
ZSH_HIGHLIGHT_STYLES[function]='fg=81'
ZSH_HIGHLIGHT_STYLES[command]='fg=75'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=214'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=244'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=81'
ZSH_HIGHLIGHT_STYLES[path]='fg=110,underline'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=110'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=244'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=214'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=178'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=141'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=141'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=173'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=114'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=114'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=114'
ZSH_HIGHLIGHT_STYLES[assign]='fg=223'
ZSH_HIGHLIGHT_STYLES[comment]='fg=244,italic'
ZSH_HIGHLIGHT_STYLES[bracket-level-1]='fg=81'
ZSH_HIGHLIGHT_STYLES[bracket-level-2]='fg=114'
ZSH_HIGHLIGHT_STYLES[bracket-level-3]='fg=214'
ZSH_HIGHLIGHT_STYLES[cursor]='standout'
