#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_FILE="$REPO_ROOT/config/modules.yaml"
OUTPUT_FILE="$REPO_ROOT/scripts/lib/module-registry-generated.sh"
DOCS_FILE="$REPO_ROOT/docs/generated/module-registry.md"

command -v ruby >/dev/null 2>&1 || {
  printf '[ERROR] ruby is required to generate module registry artifacts.\n' >&2
  exit 1
}

ruby - "$SOURCE_FILE" "$OUTPUT_FILE" "$DOCS_FILE" <<'RUBY'
# frozen_string_literal: true

require 'yaml'

source_file, output_file, docs_file = ARGV

def fail!(message)
  warn "[ERROR] #{message}"
  exit 1
end

def shell_quote(value)
  string_value = value.to_s
  return "''" if string_value.empty?

  "'#{string_value.gsub("'", %q('\''))}'"
end

def csv(items)
  Array(items).map(&:to_s).join(',')
end

def load_data(path)
  YAML.safe_load(File.read(path), permitted_classes: [], aliases: false)
rescue StandardError => e
  fail!("Failed to read #{path}: #{e.message}")
end

data = load_data(source_file)

profiles = data['profiles']
modules = data['modules']
verify_checks = data['verify_checks'] || []

fail!('profiles must be a non-empty array') unless profiles.is_a?(Array) && !profiles.empty?
fail!('modules must be a non-empty array') unless modules.is_a?(Array) && !modules.empty?
fail!('verify_checks must be an array') unless verify_checks.is_a?(Array)

profiles = profiles.map(&:to_s)
profile_set = profiles.to_h { |profile| [profile, true] }

module_ids = {}
selection_vars = []

modules.each_with_index do |module_entry, idx|
  fail!("modules[#{idx}] must be a map") unless module_entry.is_a?(Hash)

  %w[id group script enabled_profiles depends_on].each do |key|
    fail!("modules[#{idx}] missing #{key}") unless module_entry.key?(key)
  end

  module_id = module_entry['id'].to_s
  fail!("modules[#{idx}] has empty id") if module_id.empty?
  fail!("duplicate module id: #{module_id}") if module_ids[module_id]
  module_ids[module_id] = true

  selection_var = module_entry['selection_var']
  if selection_var.nil?
    module_entry['selection_var'] = ''
  else
    module_entry['selection_var'] = selection_var.to_s
    selection_vars << module_entry['selection_var'] unless module_entry['selection_var'].empty?
  end

  enabled_profiles = module_entry['enabled_profiles']
  fail!("module #{module_id} enabled_profiles must be an array") unless enabled_profiles.is_a?(Array)
  enabled_profiles.each do |profile|
    profile_name = profile.to_s
    fail!("module #{module_id} references unknown profile #{profile_name}") unless profile_set[profile_name]
  end
  module_entry['enabled_profiles'] = enabled_profiles.map(&:to_s)

  depends_on = module_entry['depends_on']
  fail!("module #{module_id} depends_on must be an array") unless depends_on.is_a?(Array)
  module_entry['depends_on'] = depends_on.map(&:to_s)
end

modules.each do |module_entry|
  module_id = module_entry['id']
  module_entry['depends_on'].each do |dependency|
    fail!("module #{module_id} depends on unknown module #{dependency}") unless module_ids[dependency]
  end
end

selection_var_set = selection_vars.uniq.sort.to_h { |var| [var, true] }

valid_check_kinds = %w[cmd file dir colima_running docker_reachable cursor_cli].to_h { |kind| [kind, true] }
valid_severities = %w[fail warn].to_h { |severity| [severity, true] }

verify_checks.each_with_index do |check, idx|
  fail!("verify_checks[#{idx}] must be a map") unless check.is_a?(Hash)

  %w[selection_var kind arg label severity].each do |key|
    fail!("verify_checks[#{idx}] missing #{key}") unless check.key?(key)
  end

  selection_var = check['selection_var'].to_s
  fail!("verify_checks[#{idx}] has unknown selection_var #{selection_var}") unless selection_var_set[selection_var]

  kind = check['kind'].to_s
  fail!("verify_checks[#{idx}] has unknown kind #{kind}") unless valid_check_kinds[kind]

  severity = check['severity'].to_s
  fail!("verify_checks[#{idx}] has unknown severity #{severity}") unless valid_severities[severity]

  check['selection_var'] = selection_var
  check['kind'] = kind
  check['arg'] = check['arg'].to_s
  check['label'] = check['label'].to_s
  check['severity'] = severity
end

profile_default_records = []
profiles.each do |profile|
  selection_var_set.keys.each do |selection_var|
    enabled = modules.any? do |module_entry|
      module_entry['selection_var'] == selection_var && module_entry['enabled_profiles'].include?(profile)
    end
    profile_default_records << "#{profile}|#{selection_var}|#{enabled ? 'true' : 'false'}"
  end
end

File.open(output_file, 'w') do |file|
  file.puts '#!/usr/bin/env bash'
  file.puts '# This file is generated by scripts/generate-module-registry.sh.'
  file.puts '# Do not edit manually.'
  file.puts

  file.puts 'REGISTRY_PROFILES=('
  profiles.each { |profile| file.puts "  #{shell_quote(profile)}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_SELECTION_VARS=('
  selection_var_set.keys.each { |selection_var| file.puts "  #{shell_quote(selection_var)}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_PROFILE_DEFAULT_RECORDS=('
  profile_default_records.each { |record| file.puts "  #{shell_quote(record)}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_MODULE_IDS=('
  modules.each { |module_entry| file.puts "  #{shell_quote(module_entry['id'])}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_MODULE_GROUPS=('
  modules.each { |module_entry| file.puts "  #{shell_quote(module_entry['group'])}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_MODULE_SCRIPTS=('
  modules.each { |module_entry| file.puts "  #{shell_quote(module_entry['script'])}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_MODULE_SELECTION_VARS=('
  modules.each { |module_entry| file.puts "  #{shell_quote(module_entry['selection_var'])}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_MODULE_ENABLED_PROFILES=('
  modules.each { |module_entry| file.puts "  #{shell_quote(csv(module_entry['enabled_profiles']))}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_MODULE_DEPENDS_ON=('
  modules.each { |module_entry| file.puts "  #{shell_quote(csv(module_entry['depends_on']))}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_VERIFY_SELECTION_VARS=('
  verify_checks.each { |check| file.puts "  #{shell_quote(check['selection_var'])}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_VERIFY_KINDS=('
  verify_checks.each { |check| file.puts "  #{shell_quote(check['kind'])}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_VERIFY_ARGS=('
  verify_checks.each { |check| file.puts "  #{shell_quote(check['arg'])}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_VERIFY_LABELS=('
  verify_checks.each { |check| file.puts "  #{shell_quote(check['label'])}" }
  file.puts ')'
  file.puts

  file.puts 'REGISTRY_VERIFY_SEVERITIES=('
  verify_checks.each { |check| file.puts "  #{shell_quote(check['severity'])}" }
  file.puts ')'
end

module_count = modules.length
check_count = verify_checks.length

File.open(docs_file, 'w') do |file|
  file.puts '# Module Registry (Generated)'
  file.puts
  file.puts "Source: `config/modules.yaml`"
  file.puts
  file.puts "- Modules: #{module_count}"
  file.puts "- Verify checks: #{check_count}"
  file.puts
  file.puts '## Modules'
  file.puts
  file.puts '| Order | Module ID | Selection Var | minimal | base | full | Group | Script | Depends On |'
  file.puts '| --- | --- | --- | --- | --- | --- | --- | --- | --- |'

  modules.each_with_index do |module_entry, index|
    profile_flags = profiles.map { |profile| module_entry['enabled_profiles'].include?(profile) ? 'yes' : 'no' }
    selection_var = module_entry['selection_var'].empty? ? '(always)' : module_entry['selection_var']
    depends_on = module_entry['depends_on'].empty? ? '-' : module_entry['depends_on'].join(', ')

    file.puts "| #{index + 1} | #{module_entry['id']} | #{selection_var} | #{profile_flags[0]} | #{profile_flags[1]} | #{profile_flags[2]} | #{module_entry['group']} | #{module_entry['script']} | #{depends_on} |"
  end

  file.puts
  file.puts '## Verify Checks'
  file.puts
  file.puts '| # | Selection Var | Kind | Severity | Label | Arg |'
  file.puts '| --- | --- | --- | --- | --- | --- |'

  verify_checks.each_with_index do |check, index|
    arg = check['arg'].empty? ? '-' : check['arg']
    file.puts "| #{index + 1} | #{check['selection_var']} | #{check['kind']} | #{check['severity']} | #{check['label']} | #{arg} |"
  end
end

puts "[OK] Generated #{output_file} and #{docs_file}"
RUBY
